const a = {
  current: {
    _children: [37],
    _internalFiberInstanceHandleDEV: {
      _debugHookTypes: null,
      _debugNeedsRemount: false,
      _debugOwner: [FiberNode],
      _debugSource: undefined,
      actualDuration: 0.0747000016272068,
      actualStartTime: 12126894.2063,
      alternate: [FiberNode],
      child: [FiberNode],
      childLanes: 0,
      deletions: null,
      dependencies: null,
      elementType: 'RCTText',
      flags: 4,
      index: 0,
      key: null,
      lanes: 0,
      memoizedProps: [Object],
      memoizedState: null,
      mode: 2,
      pendingProps: [Object],
      ref: [Circular],
      return: [FiberNode],
      selfBaseDuration: 0.03850000165402889,
      sibling: null,
      stateNode: [Circular],
      subtreeFlags: 0,
      tag: 5,
      treeBaseDuration: 0.058400001376867294,
      type: 'RCTText',
      updateQueue: null,
    },
    _nativeTag: 39,
    viewConfig: {
      Commands: [Object],
      bubblingEventTypes: [Object],
      directEventTypes: [Object],
      uiViewClassName: 'RCTText',
      validAttributes: [Object],
    },
  },
};
